/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`enums`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnumsError {
    Status400(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`fetch_study`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FetchStudyError {
    Status400(String),
    Status404(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_studies`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListStudiesError {
    Status400(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_areas`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchAreasError {
    Status400(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`studies_metadata`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StudiesMetadataError {
    Status400(String),
    UnknownValue(serde_json::Value),
}


/// Returns enumeration types and their values.  Every item of the returning array represents enum type and contains the following properties: * `type` - enum type name * `pieces` - array of names of all data pieces having the enum type * `values` - all available values of the enum; every item contains the following properties:   * `value` - data value   * `legacyValue` - data value in legacy API   * `exceptions` - map from data piece name to legacy value when different from `legacyValue`     (some data pieces had special enum values in legacy API)
pub async fn enums(configuration: &configuration::Configuration, ) -> Result<Vec<models::EnumInfo>, Error<EnumsError>> {

    let uri_str = format!("{}/studies/enums", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::EnumInfo&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::EnumInfo&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EnumsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns data of a single study.
pub async fn fetch_study(configuration: &configuration::Configuration, nct_id: &str, format: Option<&str>, markup_format: Option<&str>, fields: Option<Vec<String>>) -> Result<String, Error<FetchStudyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_nct_id = nct_id;
    let p_format = format;
    let p_markup_format = markup_format;
    let p_fields = fields;

    let uri_str = format!("{}/studies/{nctId}", configuration.base_path, nctId=crate::apis::urlencode(p_nct_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_markup_format {
        req_builder = req_builder.query(&[("markupFormat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_fields {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<FetchStudyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns data of studies matching query and filter parameters. The studies are returned page by page. If response contains `nextPageToken`, use its value in `pageToken` to get next page. The last page will not contain `nextPageToken`. A page may have empty `studies` array. Request for each subsequent page **must** have the same parameters as for the first page, except `countTotal`, `pageSize`, and `pageToken` parameters.  If neither queries nor filters are set, all studies will be returned. If any query parameter contains only NCT IDs (comma- and/or space-separated), filters are ignored.  `query.*` parameters are in [Essie expression syntax](/find-studies/constructing-complex-search-queries). Those parameters affect ranking of studies, if sorted by relevance. See `sort` parameter for details.  `filter.*` and `postFilter.*` parameters have same effect as there is no aggregation calculation.  Both are available just to simplify applying parameters from search request. Both do not affect ranking of studies.  Note: When trying JSON format in your browser, do not set too large `pageSize` parameter, if `fields` is unlimited. That may return too much data for the browser to parse and render.
pub async fn list_studies(configuration: &configuration::Configuration, format: Option<&str>, markup_format: Option<&str>, query_period_cond: Option<&str>, query_period_term: Option<&str>, query_period_locn: Option<&str>, query_period_titles: Option<&str>, query_period_intr: Option<&str>, query_period_outc: Option<&str>, query_period_spons: Option<&str>, query_period_lead: Option<&str>, query_period_id: Option<&str>, query_period_patient: Option<&str>, filter_period_overall_status: Option<Vec<models::Status>>, filter_period_geo: Option<&str>, filter_period_ids: Option<Vec<String>>, filter_period_advanced: Option<&str>, filter_period_synonyms: Option<Vec<String>>, post_filter_period_overall_status: Option<Vec<models::Status>>, post_filter_period_geo: Option<&str>, post_filter_period_ids: Option<Vec<String>>, post_filter_period_advanced: Option<&str>, post_filter_period_synonyms: Option<Vec<String>>, agg_filters: Option<&str>, geo_decay: Option<&str>, fields: Option<Vec<String>>, sort: Option<Vec<String>>, count_total: Option<bool>, page_size: Option<i32>, page_token: Option<&str>) -> Result<models::PagedStudies, Error<ListStudiesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_format = format;
    let p_markup_format = markup_format;
    let p_query_period_cond = query_period_cond;
    let p_query_period_term = query_period_term;
    let p_query_period_locn = query_period_locn;
    let p_query_period_titles = query_period_titles;
    let p_query_period_intr = query_period_intr;
    let p_query_period_outc = query_period_outc;
    let p_query_period_spons = query_period_spons;
    let p_query_period_lead = query_period_lead;
    let p_query_period_id = query_period_id;
    let p_query_period_patient = query_period_patient;
    let p_filter_period_overall_status = filter_period_overall_status;
    let p_filter_period_geo = filter_period_geo;
    let p_filter_period_ids = filter_period_ids;
    let p_filter_period_advanced = filter_period_advanced;
    let p_filter_period_synonyms = filter_period_synonyms;
    let p_post_filter_period_overall_status = post_filter_period_overall_status;
    let p_post_filter_period_geo = post_filter_period_geo;
    let p_post_filter_period_ids = post_filter_period_ids;
    let p_post_filter_period_advanced = post_filter_period_advanced;
    let p_post_filter_period_synonyms = post_filter_period_synonyms;
    let p_agg_filters = agg_filters;
    let p_geo_decay = geo_decay;
    let p_fields = fields;
    let p_sort = sort;
    let p_count_total = count_total;
    let p_page_size = page_size;
    let p_page_token = page_token;

    let uri_str = format!("{}/studies", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_format {
        req_builder = req_builder.query(&[("format", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_markup_format {
        req_builder = req_builder.query(&[("markupFormat", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_cond {
        req_builder = req_builder.query(&[("query.cond", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_term {
        req_builder = req_builder.query(&[("query.term", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_locn {
        req_builder = req_builder.query(&[("query.locn", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_titles {
        req_builder = req_builder.query(&[("query.titles", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_intr {
        req_builder = req_builder.query(&[("query.intr", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_outc {
        req_builder = req_builder.query(&[("query.outc", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_spons {
        req_builder = req_builder.query(&[("query.spons", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_lead {
        req_builder = req_builder.query(&[("query.lead", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_id {
        req_builder = req_builder.query(&[("query.id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_period_patient {
        req_builder = req_builder.query(&[("query.patient", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_period_overall_status {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.overallStatus".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.overallStatus", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_filter_period_geo {
        req_builder = req_builder.query(&[("filter.geo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_period_ids {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.ids".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.ids", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_filter_period_advanced {
        req_builder = req_builder.query(&[("filter.advanced", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_filter_period_synonyms {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("filter.synonyms".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("filter.synonyms", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_post_filter_period_overall_status {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postFilter.overallStatus".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postFilter.overallStatus", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_post_filter_period_geo {
        req_builder = req_builder.query(&[("postFilter.geo", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_post_filter_period_ids {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postFilter.ids".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postFilter.ids", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_post_filter_period_advanced {
        req_builder = req_builder.query(&[("postFilter.advanced", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_post_filter_period_synonyms {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postFilter.synonyms".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postFilter.synonyms", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_agg_filters {
        req_builder = req_builder.query(&[("aggFilters", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_geo_decay {
        req_builder = req_builder.query(&[("geoDecay", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_fields {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("fields".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("fields", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_sort {
        req_builder = match "pipes" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("sort".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("sort", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_count_total {
        req_builder = req_builder.query(&[("countTotal", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_page_size {
        req_builder = req_builder.query(&[("pageSize", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_page_token {
        req_builder = req_builder.query(&[("pageToken", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PagedStudies`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PagedStudies`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListStudiesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Search Docs and their Search Areas.
pub async fn search_areas(configuration: &configuration::Configuration, ) -> Result<Vec<models::SearchDocument>, Error<SearchAreasError>> {

    let uri_str = format!("{}/studies/search-areas", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::SearchDocument&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::SearchDocument&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SearchAreasError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns study data model fields.
pub async fn studies_metadata(configuration: &configuration::Configuration, include_indexed_only: Option<bool>, include_historic_only: Option<bool>) -> Result<Vec<models::FieldNode>, Error<StudiesMetadataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_include_indexed_only = include_indexed_only;
    let p_include_historic_only = include_historic_only;

    let uri_str = format!("{}/studies/metadata", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_include_indexed_only {
        req_builder = req_builder.query(&[("includeIndexedOnly", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_include_historic_only {
        req_builder = req_builder.query(&[("includeHistoricOnly", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::FieldNode&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::FieldNode&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StudiesMetadataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

