/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdverseEventsModule {
    #[serde(rename = "frequencyThreshold", skip_serializing_if = "Option::is_none")]
    pub frequency_threshold: Option<String>,
    #[serde(rename = "timeFrame", skip_serializing_if = "Option::is_none")]
    pub time_frame: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "allCauseMortalityComment", skip_serializing_if = "Option::is_none")]
    pub all_cause_mortality_comment: Option<String>,
    #[serde(rename = "eventGroups", skip_serializing_if = "Option::is_none")]
    pub event_groups: Option<Vec<models::EventGroup>>,
    #[serde(rename = "seriousEvents", skip_serializing_if = "Option::is_none")]
    pub serious_events: Option<Vec<models::AdverseEvent>>,
    #[serde(rename = "otherEvents", skip_serializing_if = "Option::is_none")]
    pub other_events: Option<Vec<models::AdverseEvent>>,
}

impl AdverseEventsModule {
    pub fn new() -> AdverseEventsModule {
        AdverseEventsModule {
            frequency_threshold: None,
            time_frame: None,
            description: None,
            all_cause_mortality_comment: None,
            event_groups: None,
            serious_events: None,
            other_events: None,
        }
    }
}

