/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdverseEvent {
    #[serde(rename = "term", skip_serializing_if = "Option::is_none")]
    pub term: Option<String>,
    #[serde(rename = "organSystem", skip_serializing_if = "Option::is_none")]
    pub organ_system: Option<String>,
    #[serde(rename = "sourceVocabulary", skip_serializing_if = "Option::is_none")]
    pub source_vocabulary: Option<String>,
    #[serde(rename = "assessmentType", skip_serializing_if = "Option::is_none")]
    pub assessment_type: Option<models::EventAssessment>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Vec<models::EventStats>>,
}

impl AdverseEvent {
    pub fn new() -> AdverseEvent {
        AdverseEvent {
            term: None,
            organ_system: None,
            source_vocabulary: None,
            assessment_type: None,
            notes: None,
            stats: None,
        }
    }
}

