/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgencyClass {
    #[serde(rename = "NIH")]
    Nih,
    #[serde(rename = "FED")]
    Fed,
    #[serde(rename = "OTHER_GOV")]
    OtherGov,
    #[serde(rename = "INDIV")]
    Indiv,
    #[serde(rename = "INDUSTRY")]
    Industry,
    #[serde(rename = "NETWORK")]
    Network,
    #[serde(rename = "AMBIG")]
    Ambig,
    #[serde(rename = "OTHER")]
    Other,
    #[serde(rename = "UNKNOWN")]
    Unknown,

}

impl std::fmt::Display for AgencyClass {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Nih => write!(f, "NIH"),
            Self::Fed => write!(f, "FED"),
            Self::OtherGov => write!(f, "OTHER_GOV"),
            Self::Indiv => write!(f, "INDIV"),
            Self::Industry => write!(f, "INDUSTRY"),
            Self::Network => write!(f, "NETWORK"),
            Self::Ambig => write!(f, "AMBIG"),
            Self::Other => write!(f, "OTHER"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for AgencyClass {
    fn default() -> AgencyClass {
        Self::Nih
    }
}

