/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgreementRestrictionType {
    #[serde(rename = "LTE60")]
    Lte60,
    #[serde(rename = "GT60")]
    Gt60,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for AgreementRestrictionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Lte60 => write!(f, "LTE60"),
            Self::Gt60 => write!(f, "GT60"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for AgreementRestrictionType {
    fn default() -> AgreementRestrictionType {
        Self::Lte60
    }
}

