/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AnalysisDispersionType {
    #[serde(rename = "STANDARD_DEVIATION")]
    StandardDeviation,
    #[serde(rename = "STANDARD_ERROR_OF_MEAN")]
    StandardErrorOfMean,

}

impl std::fmt::Display for AnalysisDispersionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StandardDeviation => write!(f, "STANDARD_DEVIATION"),
            Self::StandardErrorOfMean => write!(f, "STANDARD_ERROR_OF_MEAN"),
        }
    }
}

impl Default for AnalysisDispersionType {
    fn default() -> AnalysisDispersionType {
        Self::StandardDeviation
    }
}

