/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnotationModule {
    #[serde(rename = "unpostedAnnotation", skip_serializing_if = "Option::is_none")]
    pub unposted_annotation: Option<Box<models::UnpostedAnnotation>>,
    #[serde(rename = "violationAnnotation", skip_serializing_if = "Option::is_none")]
    pub violation_annotation: Option<Box<models::ViolationAnnotation>>,
}

impl AnnotationModule {
    pub fn new() -> AnnotationModule {
        AnnotationModule {
            unposted_annotation: None,
            violation_annotation: None,
        }
    }
}

