/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArmGroupType {
    #[serde(rename = "EXPERIMENTAL")]
    Experimental,
    #[serde(rename = "ACTIVE_COMPARATOR")]
    ActiveComparator,
    #[serde(rename = "PLACEBO_COMPARATOR")]
    PlaceboComparator,
    #[serde(rename = "SHAM_COMPARATOR")]
    ShamComparator,
    #[serde(rename = "NO_INTERVENTION")]
    NoIntervention,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for ArmGroupType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Experimental => write!(f, "EXPERIMENTAL"),
            Self::ActiveComparator => write!(f, "ACTIVE_COMPARATOR"),
            Self::PlaceboComparator => write!(f, "PLACEBO_COMPARATOR"),
            Self::ShamComparator => write!(f, "SHAM_COMPARATOR"),
            Self::NoIntervention => write!(f, "NO_INTERVENTION"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for ArmGroupType {
    fn default() -> ArmGroupType {
        Self::Experimental
    }
}

