/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArmsInterventionsModule {
    #[serde(rename = "armGroups", skip_serializing_if = "Option::is_none")]
    pub arm_groups: Option<Vec<models::ArmGroup>>,
    #[serde(rename = "interventions", skip_serializing_if = "Option::is_none")]
    pub interventions: Option<Vec<models::Intervention>>,
}

impl ArmsInterventionsModule {
    pub fn new() -> ArmsInterventionsModule {
        ArmsInterventionsModule {
            arm_groups: None,
            interventions: None,
        }
    }
}

