/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaselineCharacteristicsModule {
    #[serde(rename = "populationDescription", skip_serializing_if = "Option::is_none")]
    pub population_description: Option<String>,
    #[serde(rename = "typeUnitsAnalyzed", skip_serializing_if = "Option::is_none")]
    pub type_units_analyzed: Option<String>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::MeasureGroup>>,
    #[serde(rename = "denoms", skip_serializing_if = "Option::is_none")]
    pub denoms: Option<Vec<models::Denom>>,
    #[serde(rename = "measures", skip_serializing_if = "Option::is_none")]
    pub measures: Option<Vec<models::BaselineMeasure>>,
}

impl BaselineCharacteristicsModule {
    pub fn new() -> BaselineCharacteristicsModule {
        BaselineCharacteristicsModule {
            population_description: None,
            type_units_analyzed: None,
            groups: None,
            denoms: None,
            measures: None,
        }
    }
}

