/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaselineMeasure {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "populationDescription", skip_serializing_if = "Option::is_none")]
    pub population_description: Option<String>,
    #[serde(rename = "paramType", skip_serializing_if = "Option::is_none")]
    pub param_type: Option<models::MeasureParam>,
    #[serde(rename = "dispersionType", skip_serializing_if = "Option::is_none")]
    pub dispersion_type: Option<models::MeasureDispersionType>,
    #[serde(rename = "unitOfMeasure", skip_serializing_if = "Option::is_none")]
    pub unit_of_measure: Option<String>,
    #[serde(rename = "calculatePct", skip_serializing_if = "Option::is_none")]
    pub calculate_pct: Option<bool>,
    #[serde(rename = "denomUnitsSelected", skip_serializing_if = "Option::is_none")]
    pub denom_units_selected: Option<String>,
    #[serde(rename = "denoms", skip_serializing_if = "Option::is_none")]
    pub denoms: Option<Vec<models::Denom>>,
    #[serde(rename = "classes", skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<models::MeasureClass>>,
}

impl BaselineMeasure {
    pub fn new() -> BaselineMeasure {
        BaselineMeasure {
            title: None,
            description: None,
            population_description: None,
            param_type: None,
            dispersion_type: None,
            unit_of_measure: None,
            calculate_pct: None,
            denom_units_selected: None,
            denoms: None,
            classes: None,
        }
    }
}

