/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BooleanStats {
    #[serde(rename = "falseCount")]
    pub false_count: i32,
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "missingStudiesCount")]
    pub missing_studies_count: i32,
    #[serde(rename = "piece")]
    pub piece: String,
    #[serde(rename = "trueCount")]
    pub true_count: i32,
    #[serde(rename = "type")]
    pub r#type: models::FieldStatsType,
}

impl BooleanStats {
    pub fn new(false_count: i32, field: String, missing_studies_count: i32, piece: String, true_count: i32, r#type: models::FieldStatsType) -> BooleanStats {
        BooleanStats {
            false_count,
            field,
            missing_studies_count,
            piece,
            true_count,
            r#type,
        }
    }
}

