/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrowseModule {
    #[serde(rename = "meshes", skip_serializing_if = "Option::is_none")]
    pub meshes: Option<Vec<models::Mesh>>,
    #[serde(rename = "ancestors", skip_serializing_if = "Option::is_none")]
    pub ancestors: Option<Vec<models::Mesh>>,
    #[serde(rename = "browseLeaves", skip_serializing_if = "Option::is_none")]
    pub browse_leaves: Option<Vec<models::BrowseLeaf>>,
    #[serde(rename = "browseBranches", skip_serializing_if = "Option::is_none")]
    pub browse_branches: Option<Vec<models::BrowseBranch>>,
}

impl BrowseModule {
    pub fn new() -> BrowseModule {
        BrowseModule {
            meshes: None,
            ancestors: None,
            browse_leaves: None,
            browse_branches: None,
        }
    }
}

