/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrowseLeaf {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "asFound", skip_serializing_if = "Option::is_none")]
    pub as_found: Option<String>,
    #[serde(rename = "relevance", skip_serializing_if = "Option::is_none")]
    pub relevance: Option<models::BrowseLeafRelevance>,
}

impl BrowseLeaf {
    pub fn new() -> BrowseLeaf {
        BrowseLeaf {
            id: None,
            name: None,
            as_found: None,
            relevance: None,
        }
    }
}

