/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BrowseLeafRelevance {
    #[serde(rename = "LOW")]
    Low,
    #[serde(rename = "HIGH")]
    High,

}

impl std::fmt::Display for BrowseLeafRelevance {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Low => write!(f, "LOW"),
            Self::High => write!(f, "HIGH"),
        }
    }
}

impl Default for BrowseLeafRelevance {
    fn default() -> BrowseLeafRelevance {
        Self::Low
    }
}

