/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertainAgreement {
    #[serde(rename = "piSponsorEmployee", skip_serializing_if = "Option::is_none")]
    pub pi_sponsor_employee: Option<bool>,
    #[serde(rename = "restrictionType", skip_serializing_if = "Option::is_none")]
    pub restriction_type: Option<models::AgreementRestrictionType>,
    #[serde(rename = "restrictiveAgreement", skip_serializing_if = "Option::is_none")]
    pub restrictive_agreement: Option<bool>,
    #[serde(rename = "otherDetails", skip_serializing_if = "Option::is_none")]
    pub other_details: Option<String>,
}

impl CertainAgreement {
    pub fn new() -> CertainAgreement {
        CertainAgreement {
            pi_sponsor_employee: None,
            restriction_type: None,
            restrictive_agreement: None,
            other_details: None,
        }
    }
}

