/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContactsLocationsModule {
    #[serde(rename = "centralContacts", skip_serializing_if = "Option::is_none")]
    pub central_contacts: Option<Vec<models::Contact>>,
    #[serde(rename = "overallOfficials", skip_serializing_if = "Option::is_none")]
    pub overall_officials: Option<Vec<models::Official>>,
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<models::Location>>,
}

impl ContactsLocationsModule {
    pub fn new() -> ContactsLocationsModule {
        ContactsLocationsModule {
            central_contacts: None,
            overall_officials: None,
            locations: None,
        }
    }
}

