/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DerivedSection {
    #[serde(rename = "miscInfoModule", skip_serializing_if = "Option::is_none")]
    pub misc_info_module: Option<Box<models::MiscInfoModule>>,
    #[serde(rename = "conditionBrowseModule", skip_serializing_if = "Option::is_none")]
    pub condition_browse_module: Option<Box<models::BrowseModule>>,
    #[serde(rename = "interventionBrowseModule", skip_serializing_if = "Option::is_none")]
    pub intervention_browse_module: Option<Box<models::BrowseModule>>,
}

impl DerivedSection {
    pub fn new() -> DerivedSection {
        DerivedSection {
            misc_info_module: None,
            condition_browse_module: None,
            intervention_browse_module: None,
        }
    }
}

