/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescriptionModule {
    #[serde(rename = "briefSummary", skip_serializing_if = "Option::is_none")]
    pub brief_summary: Option<String>,
    #[serde(rename = "detailedDescription", skip_serializing_if = "Option::is_none")]
    pub detailed_description: Option<String>,
}

impl DescriptionModule {
    pub fn new() -> DescriptionModule {
        DescriptionModule {
            brief_summary: None,
            detailed_description: None,
        }
    }
}

