/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DesignInfo {
    #[serde(rename = "allocation", skip_serializing_if = "Option::is_none")]
    pub allocation: Option<models::DesignAllocation>,
    #[serde(rename = "interventionModel", skip_serializing_if = "Option::is_none")]
    pub intervention_model: Option<models::InterventionalAssignment>,
    #[serde(rename = "interventionModelDescription", skip_serializing_if = "Option::is_none")]
    pub intervention_model_description: Option<String>,
    #[serde(rename = "primaryPurpose", skip_serializing_if = "Option::is_none")]
    pub primary_purpose: Option<models::PrimaryPurpose>,
    #[serde(rename = "observationalModel", skip_serializing_if = "Option::is_none")]
    pub observational_model: Option<models::ObservationalModel>,
    #[serde(rename = "timePerspective", skip_serializing_if = "Option::is_none")]
    pub time_perspective: Option<models::DesignTimePerspective>,
    #[serde(rename = "maskingInfo", skip_serializing_if = "Option::is_none")]
    pub masking_info: Option<Box<models::MaskingBlock>>,
}

impl DesignInfo {
    pub fn new() -> DesignInfo {
        DesignInfo {
            allocation: None,
            intervention_model: None,
            intervention_model_description: None,
            primary_purpose: None,
            observational_model: None,
            time_perspective: None,
            masking_info: None,
        }
    }
}

