/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DesignModule {
    #[serde(rename = "studyType", skip_serializing_if = "Option::is_none")]
    pub study_type: Option<models::StudyType>,
    #[serde(rename = "nPtrsToThisExpAccNctId", skip_serializing_if = "Option::is_none")]
    pub n_ptrs_to_this_exp_acc_nct_id: Option<f64>,
    #[serde(rename = "expandedAccessTypes", skip_serializing_if = "Option::is_none")]
    pub expanded_access_types: Option<Box<models::ExpandedAccessTypes>>,
    #[serde(rename = "patientRegistry", skip_serializing_if = "Option::is_none")]
    pub patient_registry: Option<bool>,
    #[serde(rename = "targetDuration", skip_serializing_if = "Option::is_none")]
    pub target_duration: Option<String>,
    #[serde(rename = "phases", skip_serializing_if = "Option::is_none")]
    pub phases: Option<Vec<models::Phase>>,
    #[serde(rename = "designInfo", skip_serializing_if = "Option::is_none")]
    pub design_info: Option<Box<models::DesignInfo>>,
    #[serde(rename = "bioSpec", skip_serializing_if = "Option::is_none")]
    pub bio_spec: Option<Box<models::BioSpec>>,
    #[serde(rename = "enrollmentInfo", skip_serializing_if = "Option::is_none")]
    pub enrollment_info: Option<Box<models::EnrollmentInfo>>,
}

impl DesignModule {
    pub fn new() -> DesignModule {
        DesignModule {
            study_type: None,
            n_ptrs_to_this_exp_acc_nct_id: None,
            expanded_access_types: None,
            patient_registry: None,
            target_duration: None,
            phases: None,
            design_info: None,
            bio_spec: None,
            enrollment_info: None,
        }
    }
}

