/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DesignAllocation {
    #[serde(rename = "RANDOMIZED")]
    Randomized,
    #[serde(rename = "NON_RANDOMIZED")]
    NonRandomized,
    #[serde(rename = "NA")]
    Na,

}

impl std::fmt::Display for DesignAllocation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Randomized => write!(f, "RANDOMIZED"),
            Self::NonRandomized => write!(f, "NON_RANDOMIZED"),
            Self::Na => write!(f, "NA"),
        }
    }
}

impl Default for DesignAllocation {
    fn default() -> DesignAllocation {
        Self::Randomized
    }
}

