/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DesignMasking {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "SINGLE")]
    Single,
    #[serde(rename = "DOUBLE")]
    Double,
    #[serde(rename = "TRIPLE")]
    Triple,
    #[serde(rename = "QUADRUPLE")]
    Quadruple,

}

impl std::fmt::Display for DesignMasking {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "NONE"),
            Self::Single => write!(f, "SINGLE"),
            Self::Double => write!(f, "DOUBLE"),
            Self::Triple => write!(f, "TRIPLE"),
            Self::Quadruple => write!(f, "QUADRUPLE"),
        }
    }
}

impl Default for DesignMasking {
    fn default() -> DesignMasking {
        Self::None
    }
}

