/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DesignTimePerspective {
    #[serde(rename = "RETROSPECTIVE")]
    Retrospective,
    #[serde(rename = "PROSPECTIVE")]
    Prospective,
    #[serde(rename = "CROSS_SECTIONAL")]
    CrossSectional,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for DesignTimePerspective {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Retrospective => write!(f, "RETROSPECTIVE"),
            Self::Prospective => write!(f, "PROSPECTIVE"),
            Self::CrossSectional => write!(f, "CROSS_SECTIONAL"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for DesignTimePerspective {
    fn default() -> DesignTimePerspective {
        Self::Retrospective
    }
}

