/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityModule {
    #[serde(rename = "eligibilityCriteria", skip_serializing_if = "Option::is_none")]
    pub eligibility_criteria: Option<String>,
    #[serde(rename = "healthyVolunteers", skip_serializing_if = "Option::is_none")]
    pub healthy_volunteers: Option<bool>,
    #[serde(rename = "sex", skip_serializing_if = "Option::is_none")]
    pub sex: Option<models::Sex>,
    #[serde(rename = "genderBased", skip_serializing_if = "Option::is_none")]
    pub gender_based: Option<bool>,
    #[serde(rename = "genderDescription", skip_serializing_if = "Option::is_none")]
    pub gender_description: Option<String>,
    #[serde(rename = "minimumAge", skip_serializing_if = "Option::is_none")]
    pub minimum_age: Option<String>,
    #[serde(rename = "maximumAge", skip_serializing_if = "Option::is_none")]
    pub maximum_age: Option<String>,
    #[serde(rename = "stdAges", skip_serializing_if = "Option::is_none")]
    pub std_ages: Option<Vec<models::StandardAge>>,
    #[serde(rename = "studyPopulation", skip_serializing_if = "Option::is_none")]
    pub study_population: Option<String>,
    #[serde(rename = "samplingMethod", skip_serializing_if = "Option::is_none")]
    pub sampling_method: Option<models::SamplingMethod>,
}

impl EligibilityModule {
    pub fn new() -> EligibilityModule {
        EligibilityModule {
            eligibility_criteria: None,
            healthy_volunteers: None,
            sex: None,
            gender_based: None,
            gender_description: None,
            minimum_age: None,
            maximum_age: None,
            std_ages: None,
            study_population: None,
            sampling_method: None,
        }
    }
}

