/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnrollmentType {
    #[serde(rename = "ACTUAL")]
    Actual,
    #[serde(rename = "ESTIMATED")]
    Estimated,

}

impl std::fmt::Display for EnrollmentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Actual => write!(f, "ACTUAL"),
            Self::Estimated => write!(f, "ESTIMATED"),
        }
    }
}

impl Default for EnrollmentType {
    fn default() -> EnrollmentType {
        Self::Actual
    }
}

