/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnumInfo {
    #[serde(rename = "pieces")]
    pub pieces: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "values")]
    pub values: Vec<models::EnumItem>,
}

impl EnumInfo {
    pub fn new(pieces: Vec<String>, r#type: String, values: Vec<models::EnumItem>) -> EnumInfo {
        EnumInfo {
            pieces,
            r#type,
            values,
        }
    }
}

