/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnumItem {
    #[serde(rename = "exceptions", skip_serializing_if = "Option::is_none")]
    pub exceptions: Option<serde_json::Value>,
    #[serde(rename = "legacyValue")]
    pub legacy_value: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl EnumItem {
    pub fn new(legacy_value: String, value: String) -> EnumItem {
        EnumItem {
            exceptions: None,
            legacy_value,
            value,
        }
    }
}

