/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnumStats {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "missingStudiesCount")]
    pub missing_studies_count: i32,
    #[serde(rename = "piece")]
    pub piece: String,
    #[serde(rename = "topValues", skip_serializing_if = "Option::is_none")]
    pub top_values: Option<Vec<models::ValueCount>>,
    #[serde(rename = "type")]
    pub r#type: models::FieldStatsType,
    #[serde(rename = "uniqueValuesCount")]
    pub unique_values_count: i64,
}

impl EnumStats {
    pub fn new(field: String, missing_studies_count: i32, piece: String, r#type: models::FieldStatsType, unique_values_count: i64) -> EnumStats {
        EnumStats {
            field,
            missing_studies_count,
            piece,
            top_values: None,
            r#type,
            unique_values_count,
        }
    }
}

