/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventGroup {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "deathsNumAffected", skip_serializing_if = "Option::is_none")]
    pub deaths_num_affected: Option<i32>,
    #[serde(rename = "deathsNumAtRisk", skip_serializing_if = "Option::is_none")]
    pub deaths_num_at_risk: Option<i32>,
    #[serde(rename = "seriousNumAffected", skip_serializing_if = "Option::is_none")]
    pub serious_num_affected: Option<i32>,
    #[serde(rename = "seriousNumAtRisk", skip_serializing_if = "Option::is_none")]
    pub serious_num_at_risk: Option<i32>,
    #[serde(rename = "otherNumAffected", skip_serializing_if = "Option::is_none")]
    pub other_num_affected: Option<i32>,
    #[serde(rename = "otherNumAtRisk", skip_serializing_if = "Option::is_none")]
    pub other_num_at_risk: Option<i32>,
}

impl EventGroup {
    pub fn new() -> EventGroup {
        EventGroup {
            id: None,
            title: None,
            description: None,
            deaths_num_affected: None,
            deaths_num_at_risk: None,
            serious_num_affected: None,
            serious_num_at_risk: None,
            other_num_affected: None,
            other_num_at_risk: None,
        }
    }
}

