/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventStats {
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    #[serde(rename = "numEvents", skip_serializing_if = "Option::is_none")]
    pub num_events: Option<i32>,
    #[serde(rename = "numAffected", skip_serializing_if = "Option::is_none")]
    pub num_affected: Option<i32>,
    #[serde(rename = "numAtRisk", skip_serializing_if = "Option::is_none")]
    pub num_at_risk: Option<i32>,
}

impl EventStats {
    pub fn new() -> EventStats {
        EventStats {
            group_id: None,
            num_events: None,
            num_affected: None,
            num_at_risk: None,
        }
    }
}

