/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventAssessment {
    #[serde(rename = "NON_SYSTEMATIC_ASSESSMENT")]
    NonSystematicAssessment,
    #[serde(rename = "SYSTEMATIC_ASSESSMENT")]
    SystematicAssessment,

}

impl std::fmt::Display for EventAssessment {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NonSystematicAssessment => write!(f, "NON_SYSTEMATIC_ASSESSMENT"),
            Self::SystematicAssessment => write!(f, "SYSTEMATIC_ASSESSMENT"),
        }
    }
}

impl Default for EventAssessment {
    fn default() -> EventAssessment {
        Self::NonSystematicAssessment
    }
}

