/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExpandedAccessStatus {
    #[serde(rename = "AVAILABLE")]
    Available,
    #[serde(rename = "NO_LONGER_AVAILABLE")]
    NoLongerAvailable,
    #[serde(rename = "TEMPORARILY_NOT_AVAILABLE")]
    TemporarilyNotAvailable,
    #[serde(rename = "APPROVED_FOR_MARKETING")]
    ApprovedForMarketing,

}

impl std::fmt::Display for ExpandedAccessStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Available => write!(f, "AVAILABLE"),
            Self::NoLongerAvailable => write!(f, "NO_LONGER_AVAILABLE"),
            Self::TemporarilyNotAvailable => write!(f, "TEMPORARILY_NOT_AVAILABLE"),
            Self::ApprovedForMarketing => write!(f, "APPROVED_FOR_MARKETING"),
        }
    }
}

impl Default for ExpandedAccessStatus {
    fn default() -> ExpandedAccessStatus {
        Self::Available
    }
}

