/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpandedAccessTypes {
    #[serde(rename = "individual", skip_serializing_if = "Option::is_none")]
    pub individual: Option<bool>,
    #[serde(rename = "intermediate", skip_serializing_if = "Option::is_none")]
    pub intermediate: Option<bool>,
    #[serde(rename = "treatment", skip_serializing_if = "Option::is_none")]
    pub treatment: Option<bool>,
}

impl ExpandedAccessTypes {
    pub fn new() -> ExpandedAccessTypes {
        ExpandedAccessTypes {
            individual: None,
            intermediate: None,
            treatment: None,
        }
    }
}

