/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpandedAccessInfo {
    #[serde(rename = "hasExpandedAccess", skip_serializing_if = "Option::is_none")]
    pub has_expanded_access: Option<bool>,
    #[serde(rename = "nctId", skip_serializing_if = "Option::is_none")]
    pub nct_id: Option<String>,
    #[serde(rename = "statusForNctId", skip_serializing_if = "Option::is_none")]
    pub status_for_nct_id: Option<models::ExpandedAccessStatus>,
}

impl ExpandedAccessInfo {
    pub fn new() -> ExpandedAccessInfo {
        ExpandedAccessInfo {
            has_expanded_access: None,
            nct_id: None,
            status_for_nct_id: None,
        }
    }
}

