/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldNode {
    #[serde(rename = "altPieceNames", skip_serializing_if = "Option::is_none")]
    pub alt_piece_names: Option<Vec<String>>,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::FieldNode>>,
    #[serde(rename = "dedLink", skip_serializing_if = "Option::is_none")]
    pub ded_link: Option<Box<models::WebLink>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "historicOnly", skip_serializing_if = "Option::is_none")]
    pub historic_only: Option<bool>,
    #[serde(rename = "indexedOnly", skip_serializing_if = "Option::is_none")]
    pub indexed_only: Option<bool>,
    #[serde(rename = "isEnum", skip_serializing_if = "Option::is_none")]
    pub is_enum: Option<bool>,
    #[serde(rename = "maxChars", skip_serializing_if = "Option::is_none")]
    pub max_chars: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nested", skip_serializing_if = "Option::is_none")]
    pub nested: Option<bool>,
    #[serde(rename = "piece")]
    pub piece: String,
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<String>,
    #[serde(rename = "sourceType")]
    pub source_type: String,
    #[serde(rename = "synonyms", skip_serializing_if = "Option::is_none")]
    pub synonyms: Option<bool>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl FieldNode {
    pub fn new(name: String, piece: String, source_type: String, r#type: String) -> FieldNode {
        FieldNode {
            alt_piece_names: None,
            children: None,
            ded_link: None,
            description: None,
            historic_only: None,
            indexed_only: None,
            is_enum: None,
            max_chars: None,
            name,
            nested: None,
            piece,
            rules: None,
            source_type,
            synonyms: None,
            title: None,
            r#type,
        }
    }
}

