/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FieldStatsType {
    #[serde(rename = "ENUM")]
    Enum,
    #[serde(rename = "STRING")]
    String,
    #[serde(rename = "DATE")]
    Date,
    #[serde(rename = "INTEGER")]
    Integer,
    #[serde(rename = "NUMBER")]
    Number,
    #[serde(rename = "BOOLEAN")]
    Boolean,

}

impl std::fmt::Display for FieldStatsType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enum => write!(f, "ENUM"),
            Self::String => write!(f, "STRING"),
            Self::Date => write!(f, "DATE"),
            Self::Integer => write!(f, "INTEGER"),
            Self::Number => write!(f, "NUMBER"),
            Self::Boolean => write!(f, "BOOLEAN"),
        }
    }
}

impl Default for FieldStatsType {
    fn default() -> FieldStatsType {
        Self::Enum
    }
}

