/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldValuesStats {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "missingStudiesCount")]
    pub missing_studies_count: i32,
    #[serde(rename = "piece")]
    pub piece: String,
    #[serde(rename = "topValues", skip_serializing_if = "Option::is_none")]
    pub top_values: Option<Vec<models::ValueCount>>,
    #[serde(rename = "type")]
    pub r#type: models::FieldStatsType,
    #[serde(rename = "uniqueValuesCount")]
    pub unique_values_count: i64,
    #[serde(rename = "longest", skip_serializing_if = "Option::is_none")]
    pub longest: Option<Box<models::LongestString>>,
    #[serde(rename = "formats")]
    pub formats: Vec<String>,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    #[serde(rename = "avg", skip_serializing_if = "Option::is_none")]
    pub avg: Option<f64>,
    #[serde(rename = "falseCount")]
    pub false_count: i32,
    #[serde(rename = "trueCount")]
    pub true_count: i32,
}

impl FieldValuesStats {
    pub fn new(field: String, missing_studies_count: i32, piece: String, r#type: models::FieldStatsType, unique_values_count: i64, formats: Vec<String>, false_count: i32, true_count: i32) -> FieldValuesStats {
        FieldValuesStats {
            field,
            missing_studies_count,
            piece,
            top_values: None,
            r#type,
            unique_values_count,
            longest: None,
            formats,
            max: None,
            min: None,
            avg: None,
            false_count,
            true_count,
        }
    }
}

