/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FirstMcpInfo {
    #[serde(rename = "postDateStruct", skip_serializing_if = "Option::is_none")]
    pub post_date_struct: Option<Box<models::DateStruct>>,
}

impl FirstMcpInfo {
    pub fn new() -> FirstMcpInfo {
        FirstMcpInfo {
            post_date_struct: None,
        }
    }
}

