/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowMilestone {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "achievements", skip_serializing_if = "Option::is_none")]
    pub achievements: Option<Vec<models::FlowStats>>,
}

impl FlowMilestone {
    pub fn new() -> FlowMilestone {
        FlowMilestone {
            r#type: None,
            comment: None,
            achievements: None,
        }
    }
}

