/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowPeriod {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "milestones", skip_serializing_if = "Option::is_none")]
    pub milestones: Option<Vec<models::FlowMilestone>>,
    #[serde(rename = "dropWithdraws", skip_serializing_if = "Option::is_none")]
    pub drop_withdraws: Option<Vec<models::DropWithdraw>>,
}

impl FlowPeriod {
    pub fn new() -> FlowPeriod {
        FlowPeriod {
            title: None,
            milestones: None,
            drop_withdraws: None,
        }
    }
}

