/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlowStats {
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "numSubjects", skip_serializing_if = "Option::is_none")]
    pub num_subjects: Option<String>,
    #[serde(rename = "numUnits", skip_serializing_if = "Option::is_none")]
    pub num_units: Option<String>,
}

impl FlowStats {
    pub fn new() -> FlowStats {
        FlowStats {
            group_id: None,
            comment: None,
            num_subjects: None,
            num_units: None,
        }
    }
}

