/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GzipStats {
    #[serde(rename = "averageSizeBytes")]
    pub average_size_bytes: i32,
    #[serde(rename = "largestStudies")]
    pub largest_studies: Vec<models::StudySize>,
    #[serde(rename = "percentiles")]
    pub percentiles: serde_json::Value,
    #[serde(rename = "ranges")]
    pub ranges: Vec<models::DistItem>,
    #[serde(rename = "totalStudies")]
    pub total_studies: i32,
}

impl GzipStats {
    pub fn new(average_size_bytes: i32, largest_studies: Vec<models::StudySize>, percentiles: serde_json::Value, ranges: Vec<models::DistItem>, total_studies: i32) -> GzipStats {
        GzipStats {
            average_size_bytes,
            largest_studies,
            percentiles,
            ranges,
            total_studies,
        }
    }
}

