/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentificationModule {
    #[serde(rename = "nctId", skip_serializing_if = "Option::is_none")]
    pub nct_id: Option<String>,
    #[serde(rename = "nctIdAliases", skip_serializing_if = "Option::is_none")]
    pub nct_id_aliases: Option<Vec<String>>,
    #[serde(rename = "orgStudyIdInfo", skip_serializing_if = "Option::is_none")]
    pub org_study_id_info: Option<Box<models::OrgStudyIdInfo>>,
    #[serde(rename = "secondaryIdInfos", skip_serializing_if = "Option::is_none")]
    pub secondary_id_infos: Option<Vec<models::SecondaryIdInfo>>,
    #[serde(rename = "briefTitle", skip_serializing_if = "Option::is_none")]
    pub brief_title: Option<String>,
    #[serde(rename = "officialTitle", skip_serializing_if = "Option::is_none")]
    pub official_title: Option<String>,
    #[serde(rename = "acronym", skip_serializing_if = "Option::is_none")]
    pub acronym: Option<String>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<Box<models::Organization>>,
}

impl IdentificationModule {
    pub fn new() -> IdentificationModule {
        IdentificationModule {
            nct_id: None,
            nct_id_aliases: None,
            org_study_id_info: None,
            secondary_id_infos: None,
            brief_title: None,
            official_title: None,
            acronym: None,
            organization: None,
        }
    }
}

