/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InterventionType {
    #[serde(rename = "BEHAVIORAL")]
    Behavioral,
    #[serde(rename = "BIOLOGICAL")]
    Biological,
    #[serde(rename = "COMBINATION_PRODUCT")]
    CombinationProduct,
    #[serde(rename = "DEVICE")]
    Device,
    #[serde(rename = "DIAGNOSTIC_TEST")]
    DiagnosticTest,
    #[serde(rename = "DIETARY_SUPPLEMENT")]
    DietarySupplement,
    #[serde(rename = "DRUG")]
    Drug,
    #[serde(rename = "GENETIC")]
    Genetic,
    #[serde(rename = "PROCEDURE")]
    Procedure,
    #[serde(rename = "RADIATION")]
    Radiation,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for InterventionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Behavioral => write!(f, "BEHAVIORAL"),
            Self::Biological => write!(f, "BIOLOGICAL"),
            Self::CombinationProduct => write!(f, "COMBINATION_PRODUCT"),
            Self::Device => write!(f, "DEVICE"),
            Self::DiagnosticTest => write!(f, "DIAGNOSTIC_TEST"),
            Self::DietarySupplement => write!(f, "DIETARY_SUPPLEMENT"),
            Self::Drug => write!(f, "DRUG"),
            Self::Genetic => write!(f, "GENETIC"),
            Self::Procedure => write!(f, "PROCEDURE"),
            Self::Radiation => write!(f, "RADIATION"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for InterventionType {
    fn default() -> InterventionType {
        Self::Behavioral
    }
}

