/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InterventionalAssignment {
    #[serde(rename = "SINGLE_GROUP")]
    SingleGroup,
    #[serde(rename = "PARALLEL")]
    Parallel,
    #[serde(rename = "CROSSOVER")]
    Crossover,
    #[serde(rename = "FACTORIAL")]
    Factorial,
    #[serde(rename = "SEQUENTIAL")]
    Sequential,

}

impl std::fmt::Display for InterventionalAssignment {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SingleGroup => write!(f, "SINGLE_GROUP"),
            Self::Parallel => write!(f, "PARALLEL"),
            Self::Crossover => write!(f, "CROSSOVER"),
            Self::Factorial => write!(f, "FACTORIAL"),
            Self::Sequential => write!(f, "SEQUENTIAL"),
        }
    }
}

impl Default for InterventionalAssignment {
    fn default() -> InterventionalAssignment {
        Self::SingleGroup
    }
}

