/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Intervention {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::InterventionType>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "armGroupLabels", skip_serializing_if = "Option::is_none")]
    pub arm_group_labels: Option<Vec<String>>,
    #[serde(rename = "otherNames", skip_serializing_if = "Option::is_none")]
    pub other_names: Option<Vec<String>>,
}

impl Intervention {
    pub fn new() -> Intervention {
        Intervention {
            r#type: None,
            name: None,
            description: None,
            arm_group_labels: None,
            other_names: None,
        }
    }
}

