/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpdSharingStatementModule {
    #[serde(rename = "ipdSharing", skip_serializing_if = "Option::is_none")]
    pub ipd_sharing: Option<models::IpdSharing>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "infoTypes", skip_serializing_if = "Option::is_none")]
    pub info_types: Option<Vec<models::IpdSharingInfoType>>,
    #[serde(rename = "timeFrame", skip_serializing_if = "Option::is_none")]
    pub time_frame: Option<String>,
    #[serde(rename = "accessCriteria", skip_serializing_if = "Option::is_none")]
    pub access_criteria: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl IpdSharingStatementModule {
    pub fn new() -> IpdSharingStatementModule {
        IpdSharingStatementModule {
            ipd_sharing: None,
            description: None,
            info_types: None,
            time_frame: None,
            access_criteria: None,
            url: None,
        }
    }
}

