/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IpdSharingInfoType {
    #[serde(rename = "STUDY_PROTOCOL")]
    StudyProtocol,
    #[serde(rename = "SAP")]
    Sap,
    #[serde(rename = "ICF")]
    Icf,
    #[serde(rename = "CSR")]
    Csr,
    #[serde(rename = "ANALYTIC_CODE")]
    AnalyticCode,

}

impl std::fmt::Display for IpdSharingInfoType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StudyProtocol => write!(f, "STUDY_PROTOCOL"),
            Self::Sap => write!(f, "SAP"),
            Self::Icf => write!(f, "ICF"),
            Self::Csr => write!(f, "CSR"),
            Self::AnalyticCode => write!(f, "ANALYTIC_CODE"),
        }
    }
}

impl Default for IpdSharingInfoType {
    fn default() -> IpdSharingInfoType {
        Self::StudyProtocol
    }
}

