/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LargeDoc {
    #[serde(rename = "typeAbbrev", skip_serializing_if = "Option::is_none")]
    pub type_abbrev: Option<String>,
    #[serde(rename = "hasProtocol", skip_serializing_if = "Option::is_none")]
    pub has_protocol: Option<bool>,
    #[serde(rename = "hasSap", skip_serializing_if = "Option::is_none")]
    pub has_sap: Option<bool>,
    #[serde(rename = "hasIcf", skip_serializing_if = "Option::is_none")]
    pub has_icf: Option<bool>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Date and time in `yyyy-MM-dd'T'HH:mm` format
    #[serde(rename = "uploadDate", skip_serializing_if = "Option::is_none")]
    pub upload_date: Option<String>,
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl LargeDoc {
    pub fn new() -> LargeDoc {
        LargeDoc {
            type_abbrev: None,
            has_protocol: None,
            has_sap: None,
            has_icf: None,
            label: None,
            date: None,
            upload_date: None,
            filename: None,
            size: None,
        }
    }
}

