/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LargeDocumentModule {
    #[serde(rename = "noSap", skip_serializing_if = "Option::is_none")]
    pub no_sap: Option<bool>,
    #[serde(rename = "largeDocs", skip_serializing_if = "Option::is_none")]
    pub large_docs: Option<Vec<models::LargeDoc>>,
}

impl LargeDocumentModule {
    pub fn new() -> LargeDocumentModule {
        LargeDocumentModule {
            no_sap: None,
            large_docs: None,
        }
    }
}

