/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSizes {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "maxSize", skip_serializing_if = "Option::is_none")]
    pub max_size: Option<i32>,
    #[serde(rename = "minSize", skip_serializing_if = "Option::is_none")]
    pub min_size: Option<i32>,
    #[serde(rename = "piece")]
    pub piece: String,
    #[serde(rename = "topSizes", skip_serializing_if = "Option::is_none")]
    pub top_sizes: Option<Vec<models::ListSize>>,
    #[serde(rename = "uniqueSizesCount")]
    pub unique_sizes_count: i64,
}

impl ListSizes {
    pub fn new(field: String, piece: String, unique_sizes_count: i64) -> ListSizes {
        ListSizes {
            field,
            max_size: None,
            min_size: None,
            piece,
            top_sizes: None,
            unique_sizes_count,
        }
    }
}

