/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LongestString {
    #[serde(rename = "length")]
    pub length: i32,
    #[serde(rename = "nctId")]
    pub nct_id: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl LongestString {
    pub fn new(length: i32, nct_id: String, value: String) -> LongestString {
        LongestString {
            length,
            nct_id,
            value,
        }
    }
}

