/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaskingBlock {
    #[serde(rename = "masking", skip_serializing_if = "Option::is_none")]
    pub masking: Option<models::DesignMasking>,
    #[serde(rename = "maskingDescription", skip_serializing_if = "Option::is_none")]
    pub masking_description: Option<String>,
    #[serde(rename = "whoMasked", skip_serializing_if = "Option::is_none")]
    pub who_masked: Option<Vec<models::WhoMasked>>,
}

impl MaskingBlock {
    pub fn new() -> MaskingBlock {
        MaskingBlock {
            masking: None,
            masking_description: None,
            who_masked: None,
        }
    }
}

