/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeasureParam {
    #[serde(rename = "GEOMETRIC_MEAN")]
    GeometricMean,
    #[serde(rename = "GEOMETRIC_LEAST_SQUARES_MEAN")]
    GeometricLeastSquaresMean,
    #[serde(rename = "LEAST_SQUARES_MEAN")]
    LeastSquaresMean,
    #[serde(rename = "LOG_MEAN")]
    LogMean,
    #[serde(rename = "MEAN")]
    Mean,
    #[serde(rename = "MEDIAN")]
    Median,
    #[serde(rename = "NUMBER")]
    Number,
    #[serde(rename = "COUNT_OF_PARTICIPANTS")]
    CountOfParticipants,
    #[serde(rename = "COUNT_OF_UNITS")]
    CountOfUnits,

}

impl std::fmt::Display for MeasureParam {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GeometricMean => write!(f, "GEOMETRIC_MEAN"),
            Self::GeometricLeastSquaresMean => write!(f, "GEOMETRIC_LEAST_SQUARES_MEAN"),
            Self::LeastSquaresMean => write!(f, "LEAST_SQUARES_MEAN"),
            Self::LogMean => write!(f, "LOG_MEAN"),
            Self::Mean => write!(f, "MEAN"),
            Self::Median => write!(f, "MEDIAN"),
            Self::Number => write!(f, "NUMBER"),
            Self::CountOfParticipants => write!(f, "COUNT_OF_PARTICIPANTS"),
            Self::CountOfUnits => write!(f, "COUNT_OF_UNITS"),
        }
    }
}

impl Default for MeasureParam {
    fn default() -> MeasureParam {
        Self::GeometricMean
    }
}

