/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasureCategory {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "measurements", skip_serializing_if = "Option::is_none")]
    pub measurements: Option<Vec<models::Measurement>>,
}

impl MeasureCategory {
    pub fn new() -> MeasureCategory {
        MeasureCategory {
            title: None,
            measurements: None,
        }
    }
}

