/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasureAnalysis {
    #[serde(rename = "paramType", skip_serializing_if = "Option::is_none")]
    pub param_type: Option<String>,
    #[serde(rename = "paramValue", skip_serializing_if = "Option::is_none")]
    pub param_value: Option<String>,
    #[serde(rename = "dispersionType", skip_serializing_if = "Option::is_none")]
    pub dispersion_type: Option<models::AnalysisDispersionType>,
    #[serde(rename = "dispersionValue", skip_serializing_if = "Option::is_none")]
    pub dispersion_value: Option<String>,
    #[serde(rename = "statisticalMethod", skip_serializing_if = "Option::is_none")]
    pub statistical_method: Option<String>,
    #[serde(rename = "statisticalComment", skip_serializing_if = "Option::is_none")]
    pub statistical_comment: Option<String>,
    #[serde(rename = "pValue", skip_serializing_if = "Option::is_none")]
    pub p_value: Option<String>,
    #[serde(rename = "pValueComment", skip_serializing_if = "Option::is_none")]
    pub p_value_comment: Option<String>,
    #[serde(rename = "ciNumSides", skip_serializing_if = "Option::is_none")]
    pub ci_num_sides: Option<models::ConfidenceIntervalNumSides>,
    #[serde(rename = "ciPctValue", skip_serializing_if = "Option::is_none")]
    pub ci_pct_value: Option<String>,
    #[serde(rename = "ciLowerLimit", skip_serializing_if = "Option::is_none")]
    pub ci_lower_limit: Option<String>,
    #[serde(rename = "ciUpperLimit", skip_serializing_if = "Option::is_none")]
    pub ci_upper_limit: Option<String>,
    #[serde(rename = "ciLowerLimitComment", skip_serializing_if = "Option::is_none")]
    pub ci_lower_limit_comment: Option<String>,
    #[serde(rename = "ciUpperLimitComment", skip_serializing_if = "Option::is_none")]
    pub ci_upper_limit_comment: Option<String>,
    #[serde(rename = "estimateComment", skip_serializing_if = "Option::is_none")]
    pub estimate_comment: Option<String>,
    #[serde(rename = "testedNonInferiority", skip_serializing_if = "Option::is_none")]
    pub tested_non_inferiority: Option<bool>,
    #[serde(rename = "nonInferiorityType", skip_serializing_if = "Option::is_none")]
    pub non_inferiority_type: Option<models::NonInferiorityType>,
    #[serde(rename = "nonInferiorityComment", skip_serializing_if = "Option::is_none")]
    pub non_inferiority_comment: Option<String>,
    #[serde(rename = "otherAnalysisDescription", skip_serializing_if = "Option::is_none")]
    pub other_analysis_description: Option<String>,
    #[serde(rename = "groupDescription", skip_serializing_if = "Option::is_none")]
    pub group_description: Option<String>,
    #[serde(rename = "groupIds", skip_serializing_if = "Option::is_none")]
    pub group_ids: Option<Vec<String>>,
}

impl MeasureAnalysis {
    pub fn new() -> MeasureAnalysis {
        MeasureAnalysis {
            param_type: None,
            param_value: None,
            dispersion_type: None,
            dispersion_value: None,
            statistical_method: None,
            statistical_comment: None,
            p_value: None,
            p_value_comment: None,
            ci_num_sides: None,
            ci_pct_value: None,
            ci_lower_limit: None,
            ci_upper_limit: None,
            ci_lower_limit_comment: None,
            ci_upper_limit_comment: None,
            estimate_comment: None,
            tested_non_inferiority: None,
            non_inferiority_type: None,
            non_inferiority_comment: None,
            other_analysis_description: None,
            group_description: None,
            group_ids: None,
        }
    }
}

