/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Measurement {
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "spread", skip_serializing_if = "Option::is_none")]
    pub spread: Option<String>,
    #[serde(rename = "lowerLimit", skip_serializing_if = "Option::is_none")]
    pub lower_limit: Option<String>,
    #[serde(rename = "upperLimit", skip_serializing_if = "Option::is_none")]
    pub upper_limit: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl Measurement {
    pub fn new() -> Measurement {
        Measurement {
            group_id: None,
            value: None,
            spread: None,
            lower_limit: None,
            upper_limit: None,
            comment: None,
        }
    }
}

