/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeasureDispersionType {
    #[serde(rename = "NA")]
    Na,
    #[serde(rename = "STANDARD_DEVIATION")]
    StandardDeviation,
    #[serde(rename = "STANDARD_ERROR")]
    StandardError,
    #[serde(rename = "INTER_QUARTILE_RANGE")]
    InterQuartileRange,
    #[serde(rename = "FULL_RANGE")]
    FullRange,
    #[serde(rename = "CONFIDENCE_80")]
    Confidence80,
    #[serde(rename = "CONFIDENCE_90")]
    Confidence90,
    #[serde(rename = "CONFIDENCE_95")]
    Confidence95,
    #[serde(rename = "CONFIDENCE_975")]
    Confidence975,
    #[serde(rename = "CONFIDENCE_99")]
    Confidence99,
    #[serde(rename = "CONFIDENCE_OTHER")]
    ConfidenceOther,
    #[serde(rename = "GEOMETRIC_COEFFICIENT")]
    GeometricCoefficient,

}

impl std::fmt::Display for MeasureDispersionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Na => write!(f, "NA"),
            Self::StandardDeviation => write!(f, "STANDARD_DEVIATION"),
            Self::StandardError => write!(f, "STANDARD_ERROR"),
            Self::InterQuartileRange => write!(f, "INTER_QUARTILE_RANGE"),
            Self::FullRange => write!(f, "FULL_RANGE"),
            Self::Confidence80 => write!(f, "CONFIDENCE_80"),
            Self::Confidence90 => write!(f, "CONFIDENCE_90"),
            Self::Confidence95 => write!(f, "CONFIDENCE_95"),
            Self::Confidence975 => write!(f, "CONFIDENCE_975"),
            Self::Confidence99 => write!(f, "CONFIDENCE_99"),
            Self::ConfidenceOther => write!(f, "CONFIDENCE_OTHER"),
            Self::GeometricCoefficient => write!(f, "GEOMETRIC_COEFFICIENT"),
        }
    }
}

impl Default for MeasureDispersionType {
    fn default() -> MeasureDispersionType {
        Self::Na
    }
}

