/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MiscInfoModule {
    #[serde(rename = "versionHolder", skip_serializing_if = "Option::is_none")]
    pub version_holder: Option<String>,
    #[serde(rename = "removedCountries", skip_serializing_if = "Option::is_none")]
    pub removed_countries: Option<Vec<String>>,
    #[serde(rename = "submissionTracking", skip_serializing_if = "Option::is_none")]
    pub submission_tracking: Option<Box<models::SubmissionTracking>>,
}

impl MiscInfoModule {
    pub fn new() -> MiscInfoModule {
        MiscInfoModule {
            version_holder: None,
            removed_countries: None,
            submission_tracking: None,
        }
    }
}

