/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoreInfoModule {
    #[serde(rename = "limitationsAndCaveats", skip_serializing_if = "Option::is_none")]
    pub limitations_and_caveats: Option<Box<models::LimitationsAndCaveats>>,
    #[serde(rename = "certainAgreement", skip_serializing_if = "Option::is_none")]
    pub certain_agreement: Option<Box<models::CertainAgreement>>,
    #[serde(rename = "pointOfContact", skip_serializing_if = "Option::is_none")]
    pub point_of_contact: Option<Box<models::PointOfContact>>,
}

impl MoreInfoModule {
    pub fn new() -> MoreInfoModule {
        MoreInfoModule {
            limitations_and_caveats: None,
            certain_agreement: None,
            point_of_contact: None,
        }
    }
}

