/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NonInferiorityType {
    #[serde(rename = "SUPERIORITY")]
    Superiority,
    #[serde(rename = "NON_INFERIORITY")]
    NonInferiority,
    #[serde(rename = "EQUIVALENCE")]
    Equivalence,
    #[serde(rename = "OTHER")]
    Other,
    #[serde(rename = "NON_INFERIORITY_OR_EQUIVALENCE")]
    NonInferiorityOrEquivalence,
    #[serde(rename = "SUPERIORITY_OR_OTHER")]
    SuperiorityOrOther,
    #[serde(rename = "NON_INFERIORITY_OR_EQUIVALENCE_LEGACY")]
    NonInferiorityOrEquivalenceLegacy,
    #[serde(rename = "SUPERIORITY_OR_OTHER_LEGACY")]
    SuperiorityOrOtherLegacy,

}

impl std::fmt::Display for NonInferiorityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Superiority => write!(f, "SUPERIORITY"),
            Self::NonInferiority => write!(f, "NON_INFERIORITY"),
            Self::Equivalence => write!(f, "EQUIVALENCE"),
            Self::Other => write!(f, "OTHER"),
            Self::NonInferiorityOrEquivalence => write!(f, "NON_INFERIORITY_OR_EQUIVALENCE"),
            Self::SuperiorityOrOther => write!(f, "SUPERIORITY_OR_OTHER"),
            Self::NonInferiorityOrEquivalenceLegacy => write!(f, "NON_INFERIORITY_OR_EQUIVALENCE_LEGACY"),
            Self::SuperiorityOrOtherLegacy => write!(f, "SUPERIORITY_OR_OTHER_LEGACY"),
        }
    }
}

impl Default for NonInferiorityType {
    fn default() -> NonInferiorityType {
        Self::Superiority
    }
}

