/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NumberStats {
    #[serde(rename = "avg", skip_serializing_if = "Option::is_none")]
    pub avg: Option<f64>,
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    #[serde(rename = "missingStudiesCount")]
    pub missing_studies_count: i32,
    #[serde(rename = "piece")]
    pub piece: String,
    #[serde(rename = "type")]
    pub r#type: models::FieldStatsType,
}

impl NumberStats {
    pub fn new(field: String, missing_studies_count: i32, piece: String, r#type: models::FieldStatsType) -> NumberStats {
        NumberStats {
            avg: None,
            field,
            max: None,
            min: None,
            missing_studies_count,
            piece,
            r#type,
        }
    }
}

