/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ObservationalModel {
    #[serde(rename = "COHORT")]
    Cohort,
    #[serde(rename = "CASE_CONTROL")]
    CaseControl,
    #[serde(rename = "CASE_ONLY")]
    CaseOnly,
    #[serde(rename = "CASE_CROSSOVER")]
    CaseCrossover,
    #[serde(rename = "ECOLOGIC_OR_COMMUNITY")]
    EcologicOrCommunity,
    #[serde(rename = "FAMILY_BASED")]
    FamilyBased,
    #[serde(rename = "DEFINED_POPULATION")]
    DefinedPopulation,
    #[serde(rename = "NATURAL_HISTORY")]
    NaturalHistory,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for ObservationalModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cohort => write!(f, "COHORT"),
            Self::CaseControl => write!(f, "CASE_CONTROL"),
            Self::CaseOnly => write!(f, "CASE_ONLY"),
            Self::CaseCrossover => write!(f, "CASE_CROSSOVER"),
            Self::EcologicOrCommunity => write!(f, "ECOLOGIC_OR_COMMUNITY"),
            Self::FamilyBased => write!(f, "FAMILY_BASED"),
            Self::DefinedPopulation => write!(f, "DEFINED_POPULATION"),
            Self::NaturalHistory => write!(f, "NATURAL_HISTORY"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for ObservationalModel {
    fn default() -> ObservationalModel {
        Self::Cohort
    }
}

