/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OfficialRole {
    #[serde(rename = "STUDY_CHAIR")]
    StudyChair,
    #[serde(rename = "STUDY_DIRECTOR")]
    StudyDirector,
    #[serde(rename = "PRINCIPAL_INVESTIGATOR")]
    PrincipalInvestigator,
    #[serde(rename = "SUB_INVESTIGATOR")]
    SubInvestigator,

}

impl std::fmt::Display for OfficialRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StudyChair => write!(f, "STUDY_CHAIR"),
            Self::StudyDirector => write!(f, "STUDY_DIRECTOR"),
            Self::PrincipalInvestigator => write!(f, "PRINCIPAL_INVESTIGATOR"),
            Self::SubInvestigator => write!(f, "SUB_INVESTIGATOR"),
        }
    }
}

impl Default for OfficialRole {
    fn default() -> OfficialRole {
        Self::StudyChair
    }
}

