/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutcomeMeasure {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::OutcomeMeasureType>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "populationDescription", skip_serializing_if = "Option::is_none")]
    pub population_description: Option<String>,
    #[serde(rename = "reportingStatus", skip_serializing_if = "Option::is_none")]
    pub reporting_status: Option<models::ReportingStatus>,
    /// Date in `yyyy`, `yyyy-MM`, or `yyyy-MM-dd` format
    #[serde(rename = "anticipatedPostingDate", skip_serializing_if = "Option::is_none")]
    pub anticipated_posting_date: Option<String>,
    #[serde(rename = "paramType", skip_serializing_if = "Option::is_none")]
    pub param_type: Option<models::MeasureParam>,
    #[serde(rename = "dispersionType", skip_serializing_if = "Option::is_none")]
    pub dispersion_type: Option<String>,
    #[serde(rename = "unitOfMeasure", skip_serializing_if = "Option::is_none")]
    pub unit_of_measure: Option<String>,
    #[serde(rename = "calculatePct", skip_serializing_if = "Option::is_none")]
    pub calculate_pct: Option<bool>,
    #[serde(rename = "timeFrame", skip_serializing_if = "Option::is_none")]
    pub time_frame: Option<String>,
    #[serde(rename = "typeUnitsAnalyzed", skip_serializing_if = "Option::is_none")]
    pub type_units_analyzed: Option<String>,
    #[serde(rename = "denomUnitsSelected", skip_serializing_if = "Option::is_none")]
    pub denom_units_selected: Option<String>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::MeasureGroup>>,
    #[serde(rename = "denoms", skip_serializing_if = "Option::is_none")]
    pub denoms: Option<Vec<models::Denom>>,
    #[serde(rename = "classes", skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<models::MeasureClass>>,
    #[serde(rename = "analyses", skip_serializing_if = "Option::is_none")]
    pub analyses: Option<Vec<models::MeasureAnalysis>>,
}

impl OutcomeMeasure {
    pub fn new() -> OutcomeMeasure {
        OutcomeMeasure {
            r#type: None,
            title: None,
            description: None,
            population_description: None,
            reporting_status: None,
            anticipated_posting_date: None,
            param_type: None,
            dispersion_type: None,
            unit_of_measure: None,
            calculate_pct: None,
            time_frame: None,
            type_units_analyzed: None,
            denom_units_selected: None,
            groups: None,
            denoms: None,
            classes: None,
            analyses: None,
        }
    }
}

