/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutcomesModule {
    #[serde(rename = "primaryOutcomes", skip_serializing_if = "Option::is_none")]
    pub primary_outcomes: Option<Vec<models::Outcome>>,
    #[serde(rename = "secondaryOutcomes", skip_serializing_if = "Option::is_none")]
    pub secondary_outcomes: Option<Vec<models::Outcome>>,
    #[serde(rename = "otherOutcomes", skip_serializing_if = "Option::is_none")]
    pub other_outcomes: Option<Vec<models::Outcome>>,
}

impl OutcomesModule {
    pub fn new() -> OutcomesModule {
        OutcomesModule {
            primary_outcomes: None,
            secondary_outcomes: None,
            other_outcomes: None,
        }
    }
}

