/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OutcomeMeasureType {
    #[serde(rename = "PRIMARY")]
    Primary,
    #[serde(rename = "SECONDARY")]
    Secondary,
    #[serde(rename = "OTHER_PRE_SPECIFIED")]
    OtherPreSpecified,
    #[serde(rename = "POST_HOC")]
    PostHoc,

}

impl std::fmt::Display for OutcomeMeasureType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Primary => write!(f, "PRIMARY"),
            Self::Secondary => write!(f, "SECONDARY"),
            Self::OtherPreSpecified => write!(f, "OTHER_PRE_SPECIFIED"),
            Self::PostHoc => write!(f, "POST_HOC"),
        }
    }
}

impl Default for OutcomeMeasureType {
    fn default() -> OutcomeMeasureType {
        Self::Primary
    }
}

