/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OversightModule {
    #[serde(rename = "oversightHasDmc", skip_serializing_if = "Option::is_none")]
    pub oversight_has_dmc: Option<bool>,
    #[serde(rename = "isFdaRegulatedDrug", skip_serializing_if = "Option::is_none")]
    pub is_fda_regulated_drug: Option<bool>,
    #[serde(rename = "isFdaRegulatedDevice", skip_serializing_if = "Option::is_none")]
    pub is_fda_regulated_device: Option<bool>,
    #[serde(rename = "isUnapprovedDevice", skip_serializing_if = "Option::is_none")]
    pub is_unapproved_device: Option<bool>,
    #[serde(rename = "isPpsd", skip_serializing_if = "Option::is_none")]
    pub is_ppsd: Option<bool>,
    #[serde(rename = "isUsExport", skip_serializing_if = "Option::is_none")]
    pub is_us_export: Option<bool>,
    #[serde(rename = "fdaaa801Violation", skip_serializing_if = "Option::is_none")]
    pub fdaaa801_violation: Option<bool>,
}

impl OversightModule {
    pub fn new() -> OversightModule {
        OversightModule {
            oversight_has_dmc: None,
            is_fda_regulated_drug: None,
            is_fda_regulated_device: None,
            is_unapproved_device: None,
            is_ppsd: None,
            is_us_export: None,
            fdaaa801_violation: None,
        }
    }
}

