/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedStudies {
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// `study` field values of type `markup` are in markdown format. 
    #[serde(rename = "studies")]
    pub studies: Vec<models::Study>,
    #[serde(rename = "totalCount", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
}

impl PagedStudies {
    pub fn new(studies: Vec<models::Study>) -> PagedStudies {
        PagedStudies {
            next_page_token: None,
            studies,
            total_count: None,
        }
    }
}

