/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantFlowModule {
    #[serde(rename = "preAssignmentDetails", skip_serializing_if = "Option::is_none")]
    pub pre_assignment_details: Option<String>,
    #[serde(rename = "recruitmentDetails", skip_serializing_if = "Option::is_none")]
    pub recruitment_details: Option<String>,
    #[serde(rename = "typeUnitsAnalyzed", skip_serializing_if = "Option::is_none")]
    pub type_units_analyzed: Option<String>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::FlowGroup>>,
    #[serde(rename = "periods", skip_serializing_if = "Option::is_none")]
    pub periods: Option<Vec<models::FlowPeriod>>,
}

impl ParticipantFlowModule {
    pub fn new() -> ParticipantFlowModule {
        ParticipantFlowModule {
            pre_assignment_details: None,
            recruitment_details: None,
            type_units_analyzed: None,
            groups: None,
            periods: None,
        }
    }
}

