/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Phase {
    #[serde(rename = "NA")]
    Na,
    #[serde(rename = "EARLY_PHASE1")]
    EarlyPhase1,
    #[serde(rename = "PHASE1")]
    Phase1,
    #[serde(rename = "PHASE2")]
    Phase2,
    #[serde(rename = "PHASE3")]
    Phase3,
    #[serde(rename = "PHASE4")]
    Phase4,

}

impl std::fmt::Display for Phase {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Na => write!(f, "NA"),
            Self::EarlyPhase1 => write!(f, "EARLY_PHASE1"),
            Self::Phase1 => write!(f, "PHASE1"),
            Self::Phase2 => write!(f, "PHASE2"),
            Self::Phase3 => write!(f, "PHASE3"),
            Self::Phase4 => write!(f, "PHASE4"),
        }
    }
}

impl Default for Phase {
    fn default() -> Phase {
        Self::Na
    }
}

