/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrimaryPurpose {
    #[serde(rename = "TREATMENT")]
    Treatment,
    #[serde(rename = "PREVENTION")]
    Prevention,
    #[serde(rename = "DIAGNOSTIC")]
    Diagnostic,
    #[serde(rename = "ECT")]
    Ect,
    #[serde(rename = "SUPPORTIVE_CARE")]
    SupportiveCare,
    #[serde(rename = "SCREENING")]
    Screening,
    #[serde(rename = "HEALTH_SERVICES_RESEARCH")]
    HealthServicesResearch,
    #[serde(rename = "BASIC_SCIENCE")]
    BasicScience,
    #[serde(rename = "DEVICE_FEASIBILITY")]
    DeviceFeasibility,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for PrimaryPurpose {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Treatment => write!(f, "TREATMENT"),
            Self::Prevention => write!(f, "PREVENTION"),
            Self::Diagnostic => write!(f, "DIAGNOSTIC"),
            Self::Ect => write!(f, "ECT"),
            Self::SupportiveCare => write!(f, "SUPPORTIVE_CARE"),
            Self::Screening => write!(f, "SCREENING"),
            Self::HealthServicesResearch => write!(f, "HEALTH_SERVICES_RESEARCH"),
            Self::BasicScience => write!(f, "BASIC_SCIENCE"),
            Self::DeviceFeasibility => write!(f, "DEVICE_FEASIBILITY"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for PrimaryPurpose {
    fn default() -> PrimaryPurpose {
        Self::Treatment
    }
}

