/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtocolSection {
    #[serde(rename = "identificationModule", skip_serializing_if = "Option::is_none")]
    pub identification_module: Option<Box<models::IdentificationModule>>,
    #[serde(rename = "statusModule", skip_serializing_if = "Option::is_none")]
    pub status_module: Option<Box<models::StatusModule>>,
    #[serde(rename = "sponsorCollaboratorsModule", skip_serializing_if = "Option::is_none")]
    pub sponsor_collaborators_module: Option<Box<models::SponsorCollaboratorsModule>>,
    #[serde(rename = "oversightModule", skip_serializing_if = "Option::is_none")]
    pub oversight_module: Option<Box<models::OversightModule>>,
    #[serde(rename = "descriptionModule", skip_serializing_if = "Option::is_none")]
    pub description_module: Option<Box<models::DescriptionModule>>,
    #[serde(rename = "conditionsModule", skip_serializing_if = "Option::is_none")]
    pub conditions_module: Option<Box<models::ConditionsModule>>,
    #[serde(rename = "designModule", skip_serializing_if = "Option::is_none")]
    pub design_module: Option<Box<models::DesignModule>>,
    #[serde(rename = "armsInterventionsModule", skip_serializing_if = "Option::is_none")]
    pub arms_interventions_module: Option<Box<models::ArmsInterventionsModule>>,
    #[serde(rename = "outcomesModule", skip_serializing_if = "Option::is_none")]
    pub outcomes_module: Option<Box<models::OutcomesModule>>,
    #[serde(rename = "eligibilityModule", skip_serializing_if = "Option::is_none")]
    pub eligibility_module: Option<Box<models::EligibilityModule>>,
    #[serde(rename = "contactsLocationsModule", skip_serializing_if = "Option::is_none")]
    pub contacts_locations_module: Option<Box<models::ContactsLocationsModule>>,
    #[serde(rename = "referencesModule", skip_serializing_if = "Option::is_none")]
    pub references_module: Option<Box<models::ReferencesModule>>,
    #[serde(rename = "ipdSharingStatementModule", skip_serializing_if = "Option::is_none")]
    pub ipd_sharing_statement_module: Option<Box<models::IpdSharingStatementModule>>,
}

impl ProtocolSection {
    pub fn new() -> ProtocolSection {
        ProtocolSection {
            identification_module: None,
            status_module: None,
            sponsor_collaborators_module: None,
            oversight_module: None,
            description_module: None,
            conditions_module: None,
            design_module: None,
            arms_interventions_module: None,
            outcomes_module: None,
            eligibility_module: None,
            contacts_locations_module: None,
            references_module: None,
            ipd_sharing_statement_module: None,
        }
    }
}

