/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecruitmentStatus {
    #[serde(rename = "ACTIVE_NOT_RECRUITING")]
    ActiveNotRecruiting,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "ENROLLING_BY_INVITATION")]
    EnrollingByInvitation,
    #[serde(rename = "NOT_YET_RECRUITING")]
    NotYetRecruiting,
    #[serde(rename = "RECRUITING")]
    Recruiting,
    #[serde(rename = "SUSPENDED")]
    Suspended,
    #[serde(rename = "TERMINATED")]
    Terminated,
    #[serde(rename = "WITHDRAWN")]
    Withdrawn,
    #[serde(rename = "AVAILABLE")]
    Available,

}

impl std::fmt::Display for RecruitmentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ActiveNotRecruiting => write!(f, "ACTIVE_NOT_RECRUITING"),
            Self::Completed => write!(f, "COMPLETED"),
            Self::EnrollingByInvitation => write!(f, "ENROLLING_BY_INVITATION"),
            Self::NotYetRecruiting => write!(f, "NOT_YET_RECRUITING"),
            Self::Recruiting => write!(f, "RECRUITING"),
            Self::Suspended => write!(f, "SUSPENDED"),
            Self::Terminated => write!(f, "TERMINATED"),
            Self::Withdrawn => write!(f, "WITHDRAWN"),
            Self::Available => write!(f, "AVAILABLE"),
        }
    }
}

impl Default for RecruitmentStatus {
    fn default() -> RecruitmentStatus {
        Self::ActiveNotRecruiting
    }
}

