/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReferenceType {
    #[serde(rename = "BACKGROUND")]
    Background,
    #[serde(rename = "RESULT")]
    Result,
    #[serde(rename = "DERIVED")]
    Derived,

}

impl std::fmt::Display for ReferenceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Background => write!(f, "BACKGROUND"),
            Self::Result => write!(f, "RESULT"),
            Self::Derived => write!(f, "DERIVED"),
        }
    }
}

impl Default for ReferenceType {
    fn default() -> ReferenceType {
        Self::Background
    }
}

