/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reference {
    #[serde(rename = "pmid", skip_serializing_if = "Option::is_none")]
    pub pmid: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ReferenceType>,
    #[serde(rename = "citation", skip_serializing_if = "Option::is_none")]
    pub citation: Option<String>,
    #[serde(rename = "retractions", skip_serializing_if = "Option::is_none")]
    pub retractions: Option<Vec<models::Retraction>>,
}

impl Reference {
    pub fn new() -> Reference {
        Reference {
            pmid: None,
            r#type: None,
            citation: None,
            retractions: None,
        }
    }
}

