/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferencesModule {
    #[serde(rename = "references", skip_serializing_if = "Option::is_none")]
    pub references: Option<Vec<models::Reference>>,
    #[serde(rename = "seeAlsoLinks", skip_serializing_if = "Option::is_none")]
    pub see_also_links: Option<Vec<models::SeeAlsoLink>>,
    #[serde(rename = "availIpds", skip_serializing_if = "Option::is_none")]
    pub avail_ipds: Option<Vec<models::AvailIpd>>,
}

impl ReferencesModule {
    pub fn new() -> ReferencesModule {
        ReferencesModule {
            references: None,
            see_also_links: None,
            avail_ipds: None,
        }
    }
}

