/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportingStatus {
    #[serde(rename = "NOT_POSTED")]
    NotPosted,
    #[serde(rename = "POSTED")]
    Posted,

}

impl std::fmt::Display for ReportingStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NotPosted => write!(f, "NOT_POSTED"),
            Self::Posted => write!(f, "POSTED"),
        }
    }
}

impl Default for ReportingStatus {
    fn default() -> ReportingStatus {
        Self::NotPosted
    }
}

