/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponsibleParty {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ResponsiblePartyType>,
    #[serde(rename = "investigatorFullName", skip_serializing_if = "Option::is_none")]
    pub investigator_full_name: Option<String>,
    #[serde(rename = "investigatorTitle", skip_serializing_if = "Option::is_none")]
    pub investigator_title: Option<String>,
    #[serde(rename = "investigatorAffiliation", skip_serializing_if = "Option::is_none")]
    pub investigator_affiliation: Option<String>,
    #[serde(rename = "oldNameTitle", skip_serializing_if = "Option::is_none")]
    pub old_name_title: Option<String>,
    #[serde(rename = "oldOrganization", skip_serializing_if = "Option::is_none")]
    pub old_organization: Option<String>,
}

impl ResponsibleParty {
    pub fn new() -> ResponsibleParty {
        ResponsibleParty {
            r#type: None,
            investigator_full_name: None,
            investigator_title: None,
            investigator_affiliation: None,
            old_name_title: None,
            old_organization: None,
        }
    }
}

