/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResponsiblePartyType {
    #[serde(rename = "SPONSOR")]
    Sponsor,
    #[serde(rename = "PRINCIPAL_INVESTIGATOR")]
    PrincipalInvestigator,
    #[serde(rename = "SPONSOR_INVESTIGATOR")]
    SponsorInvestigator,

}

impl std::fmt::Display for ResponsiblePartyType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sponsor => write!(f, "SPONSOR"),
            Self::PrincipalInvestigator => write!(f, "PRINCIPAL_INVESTIGATOR"),
            Self::SponsorInvestigator => write!(f, "SPONSOR_INVESTIGATOR"),
        }
    }
}

impl Default for ResponsiblePartyType {
    fn default() -> ResponsiblePartyType {
        Self::Sponsor
    }
}

