/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SamplingMethod {
    #[serde(rename = "PROBABILITY_SAMPLE")]
    ProbabilitySample,
    #[serde(rename = "NON_PROBABILITY_SAMPLE")]
    NonProbabilitySample,

}

impl std::fmt::Display for SamplingMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ProbabilitySample => write!(f, "PROBABILITY_SAMPLE"),
            Self::NonProbabilitySample => write!(f, "NON_PROBABILITY_SAMPLE"),
        }
    }
}

impl Default for SamplingMethod {
    fn default() -> SamplingMethod {
        Self::ProbabilitySample
    }
}

