/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchPart {
    #[serde(rename = "isEnum")]
    pub is_enum: bool,
    #[serde(rename = "isSynonyms")]
    pub is_synonyms: bool,
    #[serde(rename = "pieces")]
    pub pieces: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "weight")]
    pub weight: f32,
}

impl SearchPart {
    pub fn new(is_enum: bool, is_synonyms: bool, pieces: Vec<String>, r#type: String, weight: f32) -> SearchPart {
        SearchPart {
            is_enum,
            is_synonyms,
            pieces,
            r#type,
            weight,
        }
    }
}

