/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchArea {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "param", skip_serializing_if = "Option::is_none")]
    pub param: Option<String>,
    #[serde(rename = "parts")]
    pub parts: Vec<models::SearchPart>,
    #[serde(rename = "uiLabel", skip_serializing_if = "Option::is_none")]
    pub ui_label: Option<String>,
}

impl SearchArea {
    pub fn new(name: String, parts: Vec<models::SearchPart>) -> SearchArea {
        SearchArea {
            name,
            param: None,
            parts,
            ui_label: None,
        }
    }
}

