/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchDocument {
    #[serde(rename = "areas")]
    pub areas: Vec<models::SearchArea>,
    #[serde(rename = "name")]
    pub name: String,
}

impl SearchDocument {
    pub fn new(areas: Vec<models::SearchArea>, name: String) -> SearchDocument {
        SearchDocument {
            areas,
            name,
        }
    }
}

