/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecondaryIdType {
    #[serde(rename = "NIH")]
    Nih,
    #[serde(rename = "FDA")]
    Fda,
    #[serde(rename = "VA")]
    Va,
    #[serde(rename = "CDC")]
    Cdc,
    #[serde(rename = "AHRQ")]
    Ahrq,
    #[serde(rename = "SAMHSA")]
    Samhsa,
    #[serde(rename = "OTHER_GRANT")]
    OtherGrant,
    #[serde(rename = "EUDRACT_NUMBER")]
    EudractNumber,
    #[serde(rename = "CTIS")]
    Ctis,
    #[serde(rename = "REGISTRY")]
    Registry,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for SecondaryIdType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Nih => write!(f, "NIH"),
            Self::Fda => write!(f, "FDA"),
            Self::Va => write!(f, "VA"),
            Self::Cdc => write!(f, "CDC"),
            Self::Ahrq => write!(f, "AHRQ"),
            Self::Samhsa => write!(f, "SAMHSA"),
            Self::OtherGrant => write!(f, "OTHER_GRANT"),
            Self::EudractNumber => write!(f, "EUDRACT_NUMBER"),
            Self::Ctis => write!(f, "CTIS"),
            Self::Registry => write!(f, "REGISTRY"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for SecondaryIdType {
    fn default() -> SecondaryIdType {
        Self::Nih
    }
}

