/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Sex {
    #[serde(rename = "FEMALE")]
    Female,
    #[serde(rename = "MALE")]
    Male,
    #[serde(rename = "ALL")]
    All,

}

impl std::fmt::Display for Sex {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Female => write!(f, "FEMALE"),
            Self::Male => write!(f, "MALE"),
            Self::All => write!(f, "ALL"),
        }
    }
}

impl Default for Sex {
    fn default() -> Sex {
        Self::Female
    }
}

