/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SponsorCollaboratorsModule {
    #[serde(rename = "responsibleParty", skip_serializing_if = "Option::is_none")]
    pub responsible_party: Option<Box<models::ResponsibleParty>>,
    #[serde(rename = "leadSponsor", skip_serializing_if = "Option::is_none")]
    pub lead_sponsor: Option<Box<models::Sponsor>>,
    #[serde(rename = "collaborators", skip_serializing_if = "Option::is_none")]
    pub collaborators: Option<Vec<models::Sponsor>>,
}

impl SponsorCollaboratorsModule {
    pub fn new() -> SponsorCollaboratorsModule {
        SponsorCollaboratorsModule {
            responsible_party: None,
            lead_sponsor: None,
            collaborators: None,
        }
    }
}

