/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StandardAge {
    #[serde(rename = "CHILD")]
    Child,
    #[serde(rename = "ADULT")]
    Adult,
    #[serde(rename = "OLDER_ADULT")]
    OlderAdult,

}

impl std::fmt::Display for StandardAge {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Child => write!(f, "CHILD"),
            Self::Adult => write!(f, "ADULT"),
            Self::OlderAdult => write!(f, "OLDER_ADULT"),
        }
    }
}

impl Default for StandardAge {
    fn default() -> StandardAge {
        Self::Child
    }
}

