/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusModule {
    /// Date in `yyyy`, `yyyy-MM`, or `yyyy-MM-dd` format
    #[serde(rename = "statusVerifiedDate", skip_serializing_if = "Option::is_none")]
    pub status_verified_date: Option<String>,
    #[serde(rename = "overallStatus", skip_serializing_if = "Option::is_none")]
    pub overall_status: Option<models::Status>,
    #[serde(rename = "lastKnownStatus", skip_serializing_if = "Option::is_none")]
    pub last_known_status: Option<models::Status>,
    #[serde(rename = "delayedPosting", skip_serializing_if = "Option::is_none")]
    pub delayed_posting: Option<bool>,
    #[serde(rename = "whyStopped", skip_serializing_if = "Option::is_none")]
    pub why_stopped: Option<String>,
    #[serde(rename = "expandedAccessInfo", skip_serializing_if = "Option::is_none")]
    pub expanded_access_info: Option<Box<models::ExpandedAccessInfo>>,
    #[serde(rename = "startDateStruct", skip_serializing_if = "Option::is_none")]
    pub start_date_struct: Option<Box<models::PartialDateStruct>>,
    #[serde(rename = "primaryCompletionDateStruct", skip_serializing_if = "Option::is_none")]
    pub primary_completion_date_struct: Option<Box<models::PartialDateStruct>>,
    #[serde(rename = "completionDateStruct", skip_serializing_if = "Option::is_none")]
    pub completion_date_struct: Option<Box<models::PartialDateStruct>>,
    #[serde(rename = "studyFirstSubmitDate", skip_serializing_if = "Option::is_none")]
    pub study_first_submit_date: Option<String>,
    #[serde(rename = "studyFirstSubmitQcDate", skip_serializing_if = "Option::is_none")]
    pub study_first_submit_qc_date: Option<String>,
    #[serde(rename = "studyFirstPostDateStruct", skip_serializing_if = "Option::is_none")]
    pub study_first_post_date_struct: Option<Box<models::DateStruct>>,
    #[serde(rename = "resultsWaived", skip_serializing_if = "Option::is_none")]
    pub results_waived: Option<bool>,
    #[serde(rename = "resultsFirstSubmitDate", skip_serializing_if = "Option::is_none")]
    pub results_first_submit_date: Option<String>,
    #[serde(rename = "resultsFirstSubmitQcDate", skip_serializing_if = "Option::is_none")]
    pub results_first_submit_qc_date: Option<String>,
    #[serde(rename = "resultsFirstPostDateStruct", skip_serializing_if = "Option::is_none")]
    pub results_first_post_date_struct: Option<Box<models::DateStruct>>,
    #[serde(rename = "dispFirstSubmitDate", skip_serializing_if = "Option::is_none")]
    pub disp_first_submit_date: Option<String>,
    #[serde(rename = "dispFirstSubmitQcDate", skip_serializing_if = "Option::is_none")]
    pub disp_first_submit_qc_date: Option<String>,
    #[serde(rename = "dispFirstPostDateStruct", skip_serializing_if = "Option::is_none")]
    pub disp_first_post_date_struct: Option<Box<models::DateStruct>>,
    #[serde(rename = "lastUpdateSubmitDate", skip_serializing_if = "Option::is_none")]
    pub last_update_submit_date: Option<String>,
    #[serde(rename = "lastUpdatePostDateStruct", skip_serializing_if = "Option::is_none")]
    pub last_update_post_date_struct: Option<Box<models::DateStruct>>,
}

impl StatusModule {
    pub fn new() -> StatusModule {
        StatusModule {
            status_verified_date: None,
            overall_status: None,
            last_known_status: None,
            delayed_posting: None,
            why_stopped: None,
            expanded_access_info: None,
            start_date_struct: None,
            primary_completion_date_struct: None,
            completion_date_struct: None,
            study_first_submit_date: None,
            study_first_submit_qc_date: None,
            study_first_post_date_struct: None,
            results_waived: None,
            results_first_submit_date: None,
            results_first_submit_qc_date: None,
            results_first_post_date_struct: None,
            disp_first_submit_date: None,
            disp_first_submit_qc_date: None,
            disp_first_post_date_struct: None,
            last_update_submit_date: None,
            last_update_post_date_struct: None,
        }
    }
}

