/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StudyType {
    #[serde(rename = "EXPANDED_ACCESS")]
    ExpandedAccess,
    #[serde(rename = "INTERVENTIONAL")]
    Interventional,
    #[serde(rename = "OBSERVATIONAL")]
    Observational,

}

impl std::fmt::Display for StudyType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ExpandedAccess => write!(f, "EXPANDED_ACCESS"),
            Self::Interventional => write!(f, "INTERVENTIONAL"),
            Self::Observational => write!(f, "OBSERVATIONAL"),
        }
    }
}

impl Default for StudyType {
    fn default() -> StudyType {
        Self::ExpandedAccess
    }
}

