/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Study {
    #[serde(rename = "protocolSection", skip_serializing_if = "Option::is_none")]
    pub protocol_section: Option<Box<models::ProtocolSection>>,
    #[serde(rename = "resultsSection", skip_serializing_if = "Option::is_none")]
    pub results_section: Option<Box<models::ResultsSection>>,
    #[serde(rename = "annotationSection", skip_serializing_if = "Option::is_none")]
    pub annotation_section: Option<Box<models::AnnotationSection>>,
    #[serde(rename = "documentSection", skip_serializing_if = "Option::is_none")]
    pub document_section: Option<Box<models::DocumentSection>>,
    #[serde(rename = "derivedSection", skip_serializing_if = "Option::is_none")]
    pub derived_section: Option<Box<models::DerivedSection>>,
    #[serde(rename = "hasResults", skip_serializing_if = "Option::is_none")]
    pub has_results: Option<bool>,
}

impl Study {
    pub fn new() -> Study {
        Study {
            protocol_section: None,
            results_section: None,
            annotation_section: None,
            document_section: None,
            derived_section: None,
            has_results: None,
        }
    }
}

