/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StudySize {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sizeBytes")]
    pub size_bytes: i32,
}

impl StudySize {
    pub fn new(id: String, size_bytes: i32) -> StudySize {
        StudySize {
            id,
            size_bytes,
        }
    }
}

