/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmissionTracking {
    #[serde(rename = "estimatedResultsFirstSubmitDate", skip_serializing_if = "Option::is_none")]
    pub estimated_results_first_submit_date: Option<String>,
    #[serde(rename = "firstMcpInfo", skip_serializing_if = "Option::is_none")]
    pub first_mcp_info: Option<Box<models::FirstMcpInfo>>,
    #[serde(rename = "submissionInfos", skip_serializing_if = "Option::is_none")]
    pub submission_infos: Option<Vec<models::SubmissionInfo>>,
}

impl SubmissionTracking {
    pub fn new() -> SubmissionTracking {
        SubmissionTracking {
            estimated_results_first_submit_date: None,
            first_mcp_info: None,
            submission_infos: None,
        }
    }
}

