/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmissionInfo {
    #[serde(rename = "releaseDate", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
    #[serde(rename = "unreleaseDate", skip_serializing_if = "Option::is_none")]
    pub unrelease_date: Option<String>,
    #[serde(rename = "unreleaseDateUnknown", skip_serializing_if = "Option::is_none")]
    pub unrelease_date_unknown: Option<bool>,
    #[serde(rename = "resetDate", skip_serializing_if = "Option::is_none")]
    pub reset_date: Option<String>,
    #[serde(rename = "mcpReleaseN", skip_serializing_if = "Option::is_none")]
    pub mcp_release_n: Option<i32>,
}

impl SubmissionInfo {
    pub fn new() -> SubmissionInfo {
        SubmissionInfo {
            release_date: None,
            unrelease_date: None,
            unrelease_date_unknown: None,
            reset_date: None,
            mcp_release_n: None,
        }
    }
}

