/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnpostedEvent {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::UnpostedEventType>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "dateUnknown", skip_serializing_if = "Option::is_none")]
    pub date_unknown: Option<bool>,
}

impl UnpostedEvent {
    pub fn new() -> UnpostedEvent {
        UnpostedEvent {
            r#type: None,
            date: None,
            date_unknown: None,
        }
    }
}

