/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnpostedEventType {
    #[serde(rename = "RESET")]
    Reset,
    #[serde(rename = "RELEASE")]
    Release,
    #[serde(rename = "UNRELEASE")]
    Unrelease,

}

impl std::fmt::Display for UnpostedEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Reset => write!(f, "RESET"),
            Self::Release => write!(f, "RELEASE"),
            Self::Unrelease => write!(f, "UNRELEASE"),
        }
    }
}

impl Default for UnpostedEventType {
    fn default() -> UnpostedEventType {
        Self::Reset
    }
}

