/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnpostedAnnotation {
    #[serde(rename = "unpostedResponsibleParty", skip_serializing_if = "Option::is_none")]
    pub unposted_responsible_party: Option<String>,
    #[serde(rename = "unpostedEvents", skip_serializing_if = "Option::is_none")]
    pub unposted_events: Option<Vec<models::UnpostedEvent>>,
}

impl UnpostedAnnotation {
    pub fn new() -> UnpostedAnnotation {
        UnpostedAnnotation {
            unposted_responsible_party: None,
            unposted_events: None,
        }
    }
}

