/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueCount {
    #[serde(rename = "studiesCount")]
    pub studies_count: i32,
    #[serde(rename = "value")]
    pub value: String,
}

impl ValueCount {
    pub fn new(studies_count: i32, value: String) -> ValueCount {
        ValueCount {
            studies_count,
            value,
        }
    }
}

