/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Version {
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    #[serde(rename = "dataTimestamp", skip_serializing_if = "Option::is_none")]
    pub data_timestamp: Option<String>,
}

impl Version {
    pub fn new(api_version: String) -> Version {
        Version {
            api_version,
            data_timestamp: None,
        }
    }
}

