/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ViolationEventType {
    #[serde(rename = "VIOLATION_IDENTIFIED")]
    ViolationIdentified,
    #[serde(rename = "CORRECTION_CONFIRMED")]
    CorrectionConfirmed,
    #[serde(rename = "PENALTY_IMPOSED")]
    PenaltyImposed,
    #[serde(rename = "ISSUES_IN_LETTER_ADDRESSED_CONFIRMED")]
    IssuesInLetterAddressedConfirmed,

}

impl std::fmt::Display for ViolationEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ViolationIdentified => write!(f, "VIOLATION_IDENTIFIED"),
            Self::CorrectionConfirmed => write!(f, "CORRECTION_CONFIRMED"),
            Self::PenaltyImposed => write!(f, "PENALTY_IMPOSED"),
            Self::IssuesInLetterAddressedConfirmed => write!(f, "ISSUES_IN_LETTER_ADDRESSED_CONFIRMED"),
        }
    }
}

impl Default for ViolationEventType {
    fn default() -> ViolationEventType {
        Self::ViolationIdentified
    }
}

