/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebLink {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl WebLink {
    pub fn new(label: String, url: String) -> WebLink {
        WebLink {
            label,
            url,
        }
    }
}

