/*
 * ClinicalTrials.gov REST API
 *
 * This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.
 *
 * The version of the OpenAPI document: 2.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WhoMasked {
    #[serde(rename = "PARTICIPANT")]
    Participant,
    #[serde(rename = "CARE_PROVIDER")]
    CareProvider,
    #[serde(rename = "INVESTIGATOR")]
    Investigator,
    #[serde(rename = "OUTCOMES_ASSESSOR")]
    OutcomesAssessor,

}

impl std::fmt::Display for WhoMasked {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Participant => write!(f, "PARTICIPANT"),
            Self::CareProvider => write!(f, "CARE_PROVIDER"),
            Self::Investigator => write!(f, "INVESTIGATOR"),
            Self::OutcomesAssessor => write!(f, "OUTCOMES_ASSESSOR"),
        }
    }
}

impl Default for WhoMasked {
    fn default() -> WhoMasked {
        Self::Participant
    }
}

